type Roasted_DataChanged {
  id: ID!
  dataKey: String!
  dataValue: String!
}

type Roasted_OperatorAuthorizationChanged {
  id: ID!
  operator: String!
  tokenOwner: String!
  tokenId: String!
  operatorNotificationData: String!
}

type Roasted_OperatorRevoked {
  id: ID!
  operator: String!
  tokenOwner: String!
  tokenId: String!
  notified: Boolean!
  operatorNotificationData: String!
}

type Roasted_OwnershipTransferred {
  id: ID!
  previousOwner: String!
  newOwner: String!
}

type Roasted_RoastPriceSet {
  id: ID!
  user: String!
  price: BigInt!
}

type Roasted_RoastTipped {
  id: ID!
  tokenId: String!
  tipper: String!
  roaster: String!
  amount: BigInt!
}

type Roasted_TokenIdDataChanged {
  id: ID!
  tokenId: String!
  dataKey: String!
  dataValue: String!
}

type Roasted_Transfer {
  id: ID!
  operator: String!
  from: String!
  to: String!
  tokenId: String!
  force: Boolean!
  data: String!
}

type Roasted_UserRoasted {
  id: ID!
  roaster: String!
  roastee: String!
  amount: BigInt!
}

type Roasted_Withdrawal {
  id: ID!
  user: String!
  amount: BigInt!
}

type User @entity
  @fulltext(
    name: "userSearch"
    language: en
    algorithm: rank
    include: [{ entity: "User", fields: [{ name: "id" }] }]
  ) {
  id: ID! # user address
  currentBalance: BigInt!
  totalWithdrawn: BigInt!
  withdrawals: [Withdrawal!]! @derivedFrom(field: "user")
  tipsGiven: [Tip!]! @derivedFrom(field: "tipper")
  lastUpdatedBlock: Int!
  lastUpdatedTimestamp: Int!
}

type RoastMetadata @entity {
  id: String! # tokenId + dataKey
  roast: Roast! # reference to the roast
  dataKey: String! # the metadata key
  dataValue: String! # the metadata value
}

type Tip @entity {
  id: ID! # tx hash + log index
  token: RoastedToken!
  tipper: User!
  roaster: String!
  amount: BigInt!
  blockNumber: Int!
  timestamp: Int!
  roast: Roast! # Add reference to the roast
}

type Roast @entity {
  id: String! # tokenId
  roaster: User! # address of who created the roast (msg.sender)
  roastee: User! # address of who got roasted
  owner: User! # current owner of the NFT
  ipfsHash: String! # IPFS hash for off-chain metadata
  tips: [Tip!]! @derivedFrom(field: "roast") # all tips received
  totalTips: BigInt! # total amount of tips received
  tipCount: Int! # number of times this roast was tipped
  createdAt: BigInt! # timestamp when roast was created
  amount: BigInt! # amount paid for the roast
}

type GlobalStats @entity {
  id: String! # "global"
  totalRoasts: Int!
  totalTips: Int!
  totalVolume: BigInt!
  totalWithdrawn: BigInt!
}

type Withdrawal @entity {
  id: ID! # tx hash + log index
  user: User!
  amount: BigInt!
  blockNumber: Int!
  timestamp: Int!
}

type RoastedToken @entity {
  id: ID! # tokenId
  totalTipsReceived: BigInt!
  tipsReceived: [Tip!]! @derivedFrom(field: "token")
  owner: String!
  lastUpdatedBlock: Int!
  lastUpdatedTimestamp: Int!
}

